name: Build (LLVM)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: mingw-w64-clang-x86_64-ninja mingw-w64-clang-x86_64-gcc mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-safetyhook git

      - name: Configure CMake
        run: |
          cmake -S . -B build/ \
            -DVCPKG_TARGET_TRIPLET=x64-mingw-static \
            -DVCPKG_HOST_TRIPLET=x64-mingw-static \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_SHARED_LINKER_FLAGS="-static -static-libstdc++ -s"

      - name: Build with CMake
        run: |
          cmake --build build/ --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omnifix-llvm-x64-static
          path: build/omnifix.dll